# Generated by Django 5.1.1 on 2024-09-29 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=100000000)),
                ('current_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
